[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80  # <- Externa (Fly recebe por aqui)

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "2s"
    grace_period = "10s"
