envVars:
  - key: DB_TYPE
    value: postgresdb
  - key: DB_POSTGRESDB_HOST
    value: db.efpotgrfqmhczkhdvwsw.supabase.co
  - key: DB_POSTGRESDB_PORT
    value: "5432"
  - key: DB_POSTGRESDB_DATABASE
    value: Miguelproject
  - key: DB_POSTGRESDB_USER
    value: postgres
  - key: DB_POSTGRESDB_PASSWORD
    value: tkbLAzufrqZOyOa9
  - key: DB_POSTGRESDB_SCHEMA
    value: n8n
  - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
    value: "false"
  - key: N8N_ENCRYPTION_KEY
    value: 5775f8694d1e2405a805200d956e15709f2079915216810ffcb4c6d7d15f970f
  - key: GENERIC_TIMEZONE
    value: America/Sao_Paulo
