services:
  - type: web
    name: n8n-render
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-render-jhyq.onrender.com
