services:
  - type: web
    name: n8n-render
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db-pool.<ID>.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: <SENHA>
      - key: DB_POSTGRESDB_SSL
        value: "true"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: DB_POSTGRESDB_SCHEMA
        value: n8n
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: N8N_ENCRYPTION_KEY
        value: miguel-key-2025
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: WEBHOOK_URL
        value: https://n8n-render.onrender.com
