plan: free
autoDeploy: true
docker:
  image: n8nio/n8n:latest
  healthCheckPath: /healthz
envVars:
  - key: N8N_PORT
    value: "5678"
  - key: N8N_PROTOCOL
    value: "https"
  - key: N8N_HOST
    value: n8n-render-qxc2.onrender.com
  - key: GENERIC_TIMEZONE
    value: America/Sao_Paulo
  - key: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - key: N8N_BASIC_AUTH_USER
    value: william.crispimm@gmail.com
  - key: N8N_BASIC_AUTH_PASSWORD
    value: Miguelmigrum2025
  - key: N8N_ENCRYPTION_KEY
    sync: false
  - key: DB_POSTGRESDB_HOST
    value: db.efpotgrfqmhczkhdvwsw.supabase.co
  - key: DB_POSTGRESDB_PORT
    value: "5432"
  - key: DB_POSTGRESDB_DATABASE
    value: postgresdb
  - key: DB_POSTGRESDB_USER
    value: postgres
  - key: DB_POSTGRESDB_PASSWORD
   sync: false
