services:
  - type: web
    name: miguel_n8n
    env: docker
    plan: free
    region: sa-east-1
    dockerfilePath: ./Dockerfile

    envVars:
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: ep-wandering-frost-acjqgsb7-pooler.sa-east-1.aws.neon.tech
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: Miguel_n8n
      - key: DB_POSTGRESDB_USER
        value: neondb_owner
      - key: DB_POSTGRESDB_PASSWORD
        value: npg_G4FxBgIR8Nme
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: 'false'
      - key: DB_POSTGRESDB_SSL
        value: 'true'
      - key: DB_POSTGRESDB_SCHEMA
        value: Miguel_n8n
      - key: N8N_ENCRYPTION_KEY
        value: 5775f8694d1e2405a805200d956e15709f2079915216810ffcb4c6d7d15f970f
      - key: WEBHOOK_TUNNEL_URL
        value: https://miguel-n8n-g4ya.onrender.com
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
